name: Daily Quote Updater

on:
  schedule:
    - cron: "0 0 * * *"   # runs once per day at midnight UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch random quote
        id: quote
        run: |
          QUOTE=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].q + " — " + .[0].a')
          echo "QUOTE=$QUOTE" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/<!--START_QUOTE-->/,<!--END_QUOTE-->/c\<!--START_QUOTE-->\n_"'$QUOTE'"_\n<!--END_QUOTE-->' README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "chore: update daily quote"
          git push
